# Importing Packages

In [77]:
#importing packages
import pandas as pd
import numpy as np

# for warnings 
import warnings
warnings.filterwarnings('ignore')

# Acquire the data

In [78]:
data = pd.read_excel("INX_Employee_Data.xls")
data.head(10)

EmpNumber  Age  Gender EducationBackground MaritalStatus    EmpDepartment  \
0  E1001000   32    Male           Marketing        Single            Sales   
1  E1001006   47    Male           Marketing        Single            Sales   
2  E1001007   40    Male       Life Sciences       Married            Sales   
3  E1001009   41    Male     Human Resources      Divorced  Human Resources   
4  E1001010   60    Male           Marketing        Single            Sales   
5  E1001011   27    Male       Life Sciences      Divorced      Development   
6  E1001016   50    Male           Marketing       Married            Sales   
7  E1001019   28  Female       Life Sciences        Single      Development   
8  E1001020   36  Female       Life Sciences       Married      Development   
9  E1001021   38  Female       Life Sciences        Single      Development   

             EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
0       Sales Executive           Travel_Rarely                10   
1       Sales Executive           Travel_Rarely                14   
2       Sales Executive       Travel_Frequently                 5   
3               Manager           Travel_Rarely                10   
4       Sales Executive           Travel_Rarely                16   
5             Developer       Travel_Frequently                10   
6  Sales Representative           Travel_Rarely                 8   
7             Developer           Travel_Rarely                 1   
8             Developer              Non-Travel                 8   
9             Developer           Travel_Rarely                 1   

   EmpEducationLevel  ...  EmpRelationshipSatisfaction  \
0                  3  ...                            4   
1                  4  ...                            4   
2                  4  ...                            3   
3                  4  ...                            2   
4                  4  ...                            4   
5                  2  ...                            3   
6                  4  ...                            4   
7                  2  ...                            4   
8                  3  ...                            1   
9                  3  ...                            4   

   TotalWorkExperienceInYears  TrainingTimesLastYear  EmpWorkLifeBalance  \
0                          10                      2                   2   
1                          20                      2                   3   
2                          20                      2                   3   
3                          23                      2                   2   
4                          10                      1                   3   
5                           9                      4                   2   
6                           4                      2                   3   
7                          10                      4                   3   
8                          10                      2                   3   
9                          10                      4                   4   

   ExperienceYearsAtThisCompany  ExperienceYearsInCurrentRole  \
0                            10                             7   
1                             7                             7   
2                            18                            13   
3                            21                             6   
4                             2                             2   
5                             9                             7   
6                             2                             2   
7                             7                             7   
8                             8                             7   
9                             1                             0   

  YearsSinceLastPromotion  YearsWithCurrManager  Attrition  PerformanceRating  
0                       0                     8         No                  3  
1                   

In [79]:
#presenting features 
data.columns

Index(['EmpNumber', 'Age', 'Gender', 'EducationBackground', 'MaritalStatus',
       'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency',
       'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction',
       'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel',
       'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime',
       'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction',
       'TotalWorkExperienceInYears', 'TrainingTimesLastYear',
       'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany',
       'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'PerformanceRating'],
      dtype='object')

In [80]:
#dropping EmpNumber column
data.drop('EmpNumber', axis =1, inplace = True)

In [81]:
data.columns

Index(['Age', 'Gender', 'EducationBackground', 'MaritalStatus',
       'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency',
       'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction',
       'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel',
       'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime',
       'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction',
       'TotalWorkExperienceInYears', 'TrainingTimesLastYear',
       'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany',
       'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'PerformanceRating'],
      dtype='object')

# Exploratory Data Analysis

# EmpDepartment

In [82]:
data.EmpDepartment.unique()

array(['Sales', 'Human Resources', 'Development', 'Data Science',
       'Research & Development', 'Finance'], dtype=object)

EmpDepartment have 6 departments.

In [83]:
data.EmpDepartment.value_counts()

Sales                     373
Development               361
Research & Development    343
Human Resources            54
Finance                    49
Data Science               20
Name: EmpDepartment, dtype: int64

# PerformanceRating

In [84]:
data.PerformanceRating.unique()

array([3, 4, 2])

PerformanceRating is having 3 unique values.

In [17]:
data.PerformanceRating.value_counts()

3    874
2    194
4    132
Name: PerformanceRating, dtype: int64

Only 13% of employees in the company were achieved level 4 - performance rating.PerformanceRating looks like imbalanced data.To do balance the data we should use SMOTE technique.

# Age

In [21]:
data.Age.unique()

array([32, 47, 40, 41, 60, 27, 50, 28, 36, 38, 44, 30, 29, 42, 34, 39, 56,
       53, 35, 52, 33, 25, 45, 23, 26, 54, 37, 24, 49, 55, 43, 51, 22, 31,
       58, 20, 21, 48, 19, 18, 59, 46, 57])

In [24]:
data.Age.value_counts().sort_values()

60     3
57     4
20     6
59     6
18     8
19     8
23     9
58    11
21    11
56    11
51    14
52    15
53    15
22    15
48    16
54    16
55    17
47    20
24    20
49    21
25    24
46    24
43    26
50    28
44    30
39    31
41    32
26    33
42    36
45    36
28    39
37    41
30    42
27    43
40    46
32    46
33    46
38    48
29    51
31    57
36    60
35    64
34    71
Name: Age, dtype: int64

In [34]:
data.loc[(data['Age']>25) & (data['Age']<45)]

Age  Gender EducationBackground MaritalStatus    EmpDepartment  \
0      32    Male           Marketing        Single            Sales   
2      40    Male       Life Sciences       Married            Sales   
3      41    Male     Human Resources      Divorced  Human Resources   
5      27    Male       Life Sciences      Divorced      Development   
7      28  Female       Life Sciences        Single      Development   
...   ...     ...                 ...           ...              ...   
1192   38  Female           Marketing        Single            Sales   
1193   29    Male       Life Sciences      Divorced      Development   
1195   27  Female             Medical      Divorced            Sales   
1196   37    Male       Life Sciences        Single      Development   
1198   34  Female             Medical        Single     Data Science   

            EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
0      Sales Executive           Travel_Rarely                10   
2      Sales Executive       Travel_Frequently                 5   
3              Manager           Travel_Rarely                10   
5            Developer       Travel_Frequently                10   
7            Developer           Travel_Rarely                 1   
...                ...                     ...               ...   
1192   Sales Executive           Travel_Rarely                 7   
1193         Developer       Travel_Frequently                 1   
1195   Sales Executive       Travel_Frequently                 3   
1196  Senior Developer           Travel_Rarely                10   
1198    Data Scientist           Travel_Rarely                 9   

      EmpEducationLevel  EmpEnvironmentSatisfaction  ...  \
0                     3                           4  ...   
2                     4                           4  ...   
3                     4                           2  ...   
5                     2                           4  ...   
7                     2                           1  ...   
...                 ...                         ...  ...   
1192                  4                           4  ...   
1193                  4                           2  ...   
1195                  1                           4  ...   
1196                  2                           4  ...   
1198                  3                           4  ...   

      EmpRelationshipSatisfaction  TotalWorkExperienceInYears  \
0                               4                          10   
2                               3                          20   
3                               2                          23   
5                               3                           9   
7                               4                          10   
...                           ...                         ...   
1192                            1                           8   
1193                            4                          10   
1195                            2                           6   
1196                            1                           4   
1198                            2                           9   

      TrainingTimesLastYear  EmpWorkLifeBalance  ExperienceYearsAtThisCompany  \
0                         2                   2                            10   
2                         2                   3                            18   
3                         2                   2                            21   
5                         4                   2                             9   
7                         4                   3                             7   
...                     ...                 ...                           ...   
1192                      2                   3                             7   
1193                      5                   3                            10   
1195                      3                   3                             6   
1196        

In [33]:
data.loc[(data['Age']>18) & (data['Age']<25)]

Age  Gender EducationBackground MaritalStatus EmpDepartment  \
29     23    Male             Medical        Single   Development   
46     24    Male       Life Sciences      Divorced   Development   
82     22    Male       Life Sciences       Married   Development   
90     24    Male       Life Sciences       Married   Development   
106    20  Female             Medical        Single         Sales   
...   ...     ...                 ...           ...           ...   
1176   21    Male    Technical Degree        Single         Sales   
1178   22    Male             Medical       Married   Development   
1188   20    Male             Medical        Single   Development   
1190   23    Male             Medical       Married   Development   
1199   24  Female       Life Sciences        Single         Sales   

                EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
29               Developer           Travel_Rarely                10   
46        Senior Developer              Non-Travel                 9   
82        Senior Developer           Travel_Rarely                 1   
90        Senior Developer              Non-Travel                 4   
106   Sales Representative           Travel_Rarely                 2   
...                    ...                     ...               ...   
1176  Sales Representative           Travel_Rarely                22   
1178             Developer           Travel_Rarely                 6   
1188      Senior Developer           Travel_Rarely                10   
1190             Developer           Travel_Rarely                 4   
1199       Sales Executive           Travel_Rarely                 3   

      EmpEducationLevel  EmpEnvironmentSatisfaction  ...  \
29                    1                           1  ...   
46                    3                           3  ...   
82                    2                           4  ...   
90                    1                           1  ...   
106                   3                           3  ...   
...                 ...                         ...  ...   
1176                  1                           3  ...   
1178                  1                           1  ...   
1188                  1                           4  ...   
1190                  3                           1  ...   
1199                  2                           1  ...   

      EmpRelationshipSatisfaction  TotalWorkExperienceInYears  \
29                              4                           2   
46                              3                           1   
82                              1                           4   
90                              4                           6   
106                             4                           2   
...                           ...                         ...   
1176                            3                           3   
1178                            4                           3   
1188                            4                           1   
1190                            1                           5   
1199                            1                           4   

      TrainingTimesLastYear  EmpWorkLifeBalance  ExperienceYearsAtThisCompany  \
29                        3                   3                             2   
46                        4                   3                             1   
82                        2                   1                             2   
90                        2                   2                             5   
106                       3                   2                             2   
...                     ...                 ...                           ...   
1176                      2                   3                             3   
1178                      3                   3                             2   
1188                      5                   3                             1   


In [35]:
data.loc[(data['Age']>45) & (data['Age']<60)]

Age  Gender EducationBackground MaritalStatus    EmpDepartment  \
1      47    Male           Marketing        Single            Sales   
6      50    Male           Marketing       Married            Sales   
11     47  Female             Medical      Divorced            Sales   
17     56    Male             Medical       Married      Development   
21     53    Male       Life Sciences        Single      Development   
...   ...     ...                 ...           ...              ...   
1160   50    Male             Medical       Married  Human Resources   
1172   48  Female       Life Sciences       Married      Development   
1186   54    Male             Medical       Married  Human Resources   
1194   48    Male           Marketing       Married            Sales   
1197   50    Male             Medical       Married      Development   

                EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
1          Sales Executive           Travel_Rarely                14   
6     Sales Representative           Travel_Rarely                 8   
11         Sales Executive       Travel_Frequently                 3   
17               Developer           Travel_Rarely                 9   
21               Developer           Travel_Rarely                 6   
...                    ...                     ...               ...   
1160               Manager       Travel_Frequently                 3   
1172      Senior Developer           Travel_Rarely                 1   
1186       Human Resources           Travel_Rarely                19   
1194       Sales Executive           Travel_Rarely                 2   
1197      Senior Developer           Travel_Rarely                28   

      EmpEducationLevel  EmpEnvironmentSatisfaction  ...  \
1                     4                           4  ...   
6                     4                           4  ...   
11                    3                           4  ...   
17                    3                           3  ...   
21                    3                           4  ...   
...                 ...                         ...  ...   
1160                  3                           1  ...   
1172                  4                           4  ...   
1186                  4                           3  ...   
1194                  1                           2  ...   
1197                  1                           4  ...   

      EmpRelationshipSatisfaction  TotalWorkExperienceInYears  \
1                               4                          20   
6                               4                           4   
11                              4                          28   
17                              3                          30   
21                              4                          19   
...                           ...                         ...   
1160                            3                          32   
1172                            1                          21   
1186                            3                          16   
1194                            4                          12   
1197                            3                          20   

      TrainingTimesLastYear  EmpWorkLifeBalance  ExperienceYearsAtThisCompany  \
1                         2                   3                             7   
6                         2                   3                             2   
11                        2                   2                            22   
17                        1                   2                            10   
21                        4                   3                             2   
...                     ...                 ...                           ...   
1160                      2                   3                            32   
1172                      3                   1                             3   
1186                      1                  

The age distribution is starting from 18 to 60 where the most of the employees are lying between 25 to 45 age count.


# Gender

In [36]:
data.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [37]:
data.Gender.value_counts()

Male      725
Female    475
Name: Gender, dtype: int64

The Gender variance is divided by 60% of Male employees and 40% of Female employees in the company.

# EmpJobRole

In [39]:
data.EmpJobRole.unique()

array(['Sales Executive', 'Manager', 'Developer', 'Sales Representative',
       'Human Resources', 'Senior Developer', 'Data Scientist',
       'Senior Manager R&D', 'Laboratory Technician',
       'Manufacturing Director', 'Research Scientist',
       'Healthcare Representative', 'Research Director', 'Manager R&D',
       'Finance Manager', 'Technical Architect', 'Business Analyst',
       'Technical Lead', 'Delivery Manager'], dtype=object)

In [40]:
data.EmpJobRole.value_counts()

Sales Executive              270
Developer                    236
Manager R&D                   94
Research Scientist            77
Sales Representative          69
Laboratory Technician         64
Senior Developer              52
Manager                       51
Finance Manager               49
Human Resources               45
Technical Lead                38
Manufacturing Director        33
Healthcare Representative     33
Data Scientist                20
Research Director             19
Business Analyst              16
Senior Manager R&D            15
Delivery Manager              12
Technical Architect            7
Name: EmpJobRole, dtype: int64

# DistanceFromHome

In [41]:
data.DistanceFromHome.unique()

array([10, 14,  5, 16,  8,  1, 24,  3, 27, 19,  9,  2,  7,  6, 26, 11, 23,
       13, 29, 12,  4, 25, 21, 18, 20, 17, 22, 28, 15])

In [42]:
data.DistanceFromHome.value_counts()

2     184
1     170
8      69
3      67
10     66
9      66
7      65
5      54
4      51
6      46
16     25
11     25
18     24
24     23
29     23
23     22
26     22
28     20
25     19
20     19
19     18
14     17
17     17
22     17
15     17
12     16
21     15
13     14
27      9
Name: DistanceFromHome, dtype: int64

The distance from home to office is distributing from 1 unit to 29 unit which can be kilometre or mile. The most of the employees are coming from the range of 1 to 10 units.

# EmpEnvironmentSatisfaction

In [43]:
data.EmpEnvironmentSatisfaction.unique()

array([4, 2, 1, 3])

In [44]:
data.EmpEnvironmentSatisfaction.value_counts()

3    367
4    361
2    242
1    230
Name: EmpEnvironmentSatisfaction, dtype: int64

The Job satisfaction level in this company is high level for the majority of employees.

# EmpHourlyRate

In [48]:
data.EmpHourlyRate.unique()

array([ 55,  42,  48,  73,  84,  32,  54,  67,  63,  81,  49,  99,  57,
        96,  44,  86,  83,  61,  80,  31,  46,  79,  77,  60,  76,  41,
        71,  66,  38,  72,  95,  82,  75,  93,  64,  36,  69,  33,  35,
        40,  43,  51,  52,  98,  45,  37,  94,  59,  88,  50,  65,  53,
        56,  78,  74,  91,  62,  87,  68,  34,  70, 100,  92,  39,  97,
        47,  90,  85,  30,  58,  89])

In [58]:
data.EmpHourlyRate.value_counts()

66    25
79    25
42    24
57    23
46    23
      ..
49    12
47    11
38    10
89     8
34     6
Name: EmpHourlyRate, Length: 71, dtype: int64

In [59]:
data.loc[(data['EmpHourlyRate']>60) & (data['EmpHourlyRate']<100)]

Age  Gender EducationBackground MaritalStatus    EmpDepartment  \
3      41    Male     Human Resources      Divorced  Human Resources   
4      60    Male           Marketing        Single            Sales   
7      28  Female       Life Sciences        Single      Development   
8      36  Female       Life Sciences       Married      Development   
9      38  Female       Life Sciences        Single      Development   
...   ...     ...                 ...           ...              ...   
1193   29    Male       Life Sciences      Divorced      Development   
1195   27  Female             Medical      Divorced            Sales   
1196   37    Male       Life Sciences        Single      Development   
1197   50    Male             Medical       Married      Development   
1199   24  Female       Life Sciences        Single            Sales   

            EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
3              Manager           Travel_Rarely                10   
4      Sales Executive           Travel_Rarely                16   
7            Developer           Travel_Rarely                 1   
8            Developer              Non-Travel                 8   
9            Developer           Travel_Rarely                 1   
...                ...                     ...               ...   
1193         Developer       Travel_Frequently                 1   
1195   Sales Executive       Travel_Frequently                 3   
1196  Senior Developer           Travel_Rarely                10   
1197  Senior Developer           Travel_Rarely                28   
1199   Sales Executive           Travel_Rarely                 3   

      EmpEducationLevel  EmpEnvironmentSatisfaction  ...  \
3                     4                           2  ...   
4                     4                           1  ...   
7                     2                           1  ...   
8                     3                           1  ...   
9                     3                           3  ...   
...                 ...                         ...  ...   
1193                  4                           2  ...   
1195                  1                           4  ...   
1196                  2                           4  ...   
1197                  1                           4  ...   
1199                  2                           1  ...   

      EmpRelationshipSatisfaction  TotalWorkExperienceInYears  \
3                               2                          23   
4                               4                          10   
7                               4                          10   
8                               1                          10   
9                               4                          10   
...                           ...                         ...   
1193                            4                          10   
1195                            2                           6   
1196                            1                           4   
1197                            3                          20   
1199                            1                           4   

      TrainingTimesLastYear  EmpWorkLifeBalance  ExperienceYearsAtThisCompany  \
3                         2                   2                            21   
4                         1                   3                             2   
7                         4                   3                             7   
8                         2                   3                             8   
9                         4                   4                             1   
...                     ...                 ...                           ...   
1193                      5                   3                            10   
1195                      3                   3                             6   
1196                      2                   3                             1   
1197        

In [60]:
data.loc[(data['EmpHourlyRate']>40) & (data['EmpHourlyRate']<60)]

Age  Gender EducationBackground MaritalStatus EmpDepartment  \
0      32    Male           Marketing        Single         Sales   
1      47    Male           Marketing        Single         Sales   
2      40    Male       Life Sciences       Married         Sales   
6      50    Male           Marketing       Married         Sales   
10     44    Male             Medical        Single   Development   
...   ...     ...                 ...           ...           ...   
1190   23    Male             Medical       Married   Development   
1191   25    Male       Life Sciences       Married         Sales   
1192   38  Female           Marketing        Single         Sales   
1194   48    Male           Marketing       Married         Sales   
1198   34  Female             Medical        Single  Data Science   

                EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
0          Sales Executive           Travel_Rarely                10   
1          Sales Executive           Travel_Rarely                14   
2          Sales Executive       Travel_Frequently                 5   
6     Sales Representative           Travel_Rarely                 8   
10               Developer              Non-Travel                24   
...                    ...                     ...               ...   
1190             Developer           Travel_Rarely                 4   
1191       Sales Executive           Travel_Rarely                 8   
1192       Sales Executive           Travel_Rarely                 7   
1194       Sales Executive           Travel_Rarely                 2   
1198        Data Scientist           Travel_Rarely                 9   

      EmpEducationLevel  EmpEnvironmentSatisfaction  ...  \
0                     3                           4  ...   
1                     4                           4  ...   
2                     4                           4  ...   
6                     4                           4  ...   
10                    3                           1  ...   
...                 ...                         ...  ...   
1190                  3                           1  ...   
1191                  3                           4  ...   
1192                  4                           4  ...   
1194                  1                           2  ...   
1198                  3                           4  ...   

      EmpRelationshipSatisfaction  TotalWorkExperienceInYears  \
0                               4                          10   
1                               4                          20   
2                               3                          20   
6                               4                           4   
10                              3                           9   
...                           ...                         ...   
1190                            1                           5   
1191                            3                           4   
1192                            1                           8   
1194                            4                          12   
1198                            2                           9   

      TrainingTimesLastYear  EmpWorkLifeBalance  ExperienceYearsAtThisCompany  \
0                         2                   2                            10   
1                         2                   3                             7   
2                         2                   3                            18   
6                         2                   3                             2   
10                        5                   3                             5   
...                     ...                 ...                           ...   
1190                      3                   4                             3   
1191                      4                   3                             3   
1192                      2                   3                             7   


In [61]:
data.loc[(data['EmpHourlyRate']<40)]

Age  Gender EducationBackground MaritalStatus EmpDepartment  \
5      27    Male       Life Sciences      Divorced   Development   
24     34  Female       Life Sciences      Divorced   Development   
25     52    Male           Marketing       Married         Sales   
27     25  Female             Medical        Single         Sales   
36     26    Male    Technical Degree        Single         Sales   
...   ...     ...                 ...           ...           ...   
1134   48  Female           Marketing       Married         Sales   
1174   34  Female    Technical Degree      Divorced         Sales   
1177   44    Male               Other       Married   Development   
1183   37    Male               Other       Married   Development   
1188   20    Male             Medical        Single   Development   

                EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
5                Developer       Travel_Frequently                10   
24               Developer           Travel_Rarely                 8   
25                 Manager           Travel_Rarely                 3   
27         Sales Executive           Travel_Rarely                26   
36         Sales Executive           Travel_Rarely                 8   
...                    ...                     ...               ...   
1134       Sales Executive           Travel_Rarely                 2   
1174  Sales Representative           Travel_Rarely                14   
1177      Senior Developer           Travel_Rarely                 3   
1183             Developer           Travel_Rarely                 3   
1188      Senior Developer           Travel_Rarely                10   

      EmpEducationLevel  EmpEnvironmentSatisfaction  ...  \
5                     2                           4  ...   
24                    5                           2  ...   
25                    4                           3  ...   
27                    1                           3  ...   
36                    3                           4  ...   
...                 ...                         ...  ...   
1134                  5                           2  ...   
1174                  3                           3  ...   
1177                  4                           4  ...   
1183                  3                           3  ...   
1188                  1                           4  ...   

      EmpRelationshipSatisfaction  TotalWorkExperienceInYears  \
5                               3                           9   
24                              3                           7   
25                              1                          34   
27                              2                           6   
36                              3                           6   
...                           ...                         ...   
1134                            1                          14   
1174                            4                           8   
1177                            1                          26   
1183                            3                          10   
1188                            4                           1   

      TrainingTimesLastYear  EmpWorkLifeBalance  ExperienceYearsAtThisCompany  \
5                         4                   2                             9   
24                        3                   3                             0   
25                        3                   4                            34   
27                        5                   2                             6   
36                        2                   2                             4   
...                     ...                 ...                           ...   
1134                      2                   3                             9   
1174                      3                   3                             8   
1177                      2                   4                             2   


The hourly rate range is 60 to 100 for majority employees work in this company.

# EmpJobInvolvement

In [62]:
data.EmpJobInvolvement.unique()

array([3, 2, 1, 4])

In [63]:
data.EmpJobInvolvement.value_counts()

3    724
2    294
4    112
1     70
Name: EmpJobInvolvement, dtype: int64

The Employee Job involvement level in this company is high level for the majority of employees.

# EmpJobSatisfaction

In [64]:
data.EmpJobSatisfaction.unique()

array([4, 1, 2, 3])

In [65]:
data.EmpJobSatisfaction.value_counts()

4    378
3    354
2    237
1    231
Name: EmpJobSatisfaction, dtype: int64

The Job satisfaction level in this company is high level for the majority of employees

# OverTime

In [66]:
data.OverTime.unique()

array(['No', 'Yes'], dtype=object)

In [67]:
data.OverTime.value_counts()

No     847
Yes    353
Name: OverTime, dtype: int64

The overall percentage of employees doing overtime is 30%

# EmpLastSalaryHikePercent

In [68]:
data.EmpLastSalaryHikePercent.unique()

array([12, 21, 15, 14, 13, 23, 11, 20, 19, 17, 18, 22, 16, 24, 25])

In [69]:
data.EmpLastSalaryHikePercent.value_counts()

14    172
11    169
13    168
12    155
15     82
18     73
16     68
17     67
19     63
20     50
22     47
21     34
23     21
24     18
25     13
Name: EmpLastSalaryHikePercent, dtype: int64

Most of the employees get 11% to 15% of salary hike in this company.

# EmpWorkLifeBalance

In [70]:
data.EmpWorkLifeBalance.unique()

array([2, 3, 4, 1])

In [71]:
data.EmpWorkLifeBalance.value_counts()

3    727
2    294
4    115
1     64
Name: EmpWorkLifeBalance, dtype: int64

Employee work life balance level is 11% in 4th level and 72% in 3rd level.

# YearsSinceLastPromotion

In [72]:
data.YearsSinceLastPromotion.unique()

array([ 0,  1, 12,  2,  3, 11,  7,  4,  5, 14,  8, 15,  6, 10, 13,  9])

In [73]:
data.YearsSinceLastPromotion.value_counts()

0     469
1     297
2     127
7      62
4      53
3      45
5      35
6      24
11     23
9      16
8      11
15     11
12      9
13      8
14      5
10      5
Name: YearsSinceLastPromotion, dtype: int64

Most of the Employees got their promotion from 0 to 2 years.Some of the employees got their promotions after long years.

# Attrition

In [74]:
data.Attrition.unique()

array(['No', 'Yes'], dtype=object)

In [75]:
data.Attrition.value_counts()

No     1022
Yes     178
Name: Attrition, dtype: int64

The 85% of employees are not having attrition in their work

# Analyzing Correlation

In [76]:
data.corr()

Age  DistanceFromHome  EmpEducationLevel  \
Age                           1.000000          0.020937           0.207313   
DistanceFromHome              0.020937          1.000000           0.045856   
EmpEducationLevel             0.207313          0.045856           1.000000   
EmpEnvironmentSatisfaction    0.013814         -0.017719          -0.037103   
EmpHourlyRate                 0.062867          0.013730           0.014095   
EmpJobInvolvement             0.027216          0.003231           0.027544   
EmpJobLevel                   0.509139          0.017270           0.100734   
EmpJobSatisfaction           -0.002436         -0.003036           0.000357   
NumCompaniesWorked            0.284408         -0.021411           0.128674   
EmpLastSalaryHikePercent     -0.006105          0.044974           0.002358   
EmpRelationshipSatisfaction   0.049749         -0.009509          -0.016690   
TotalWorkExperienceInYears    0.680886          0.027306           0.151062   
TrainingTimesLastYear        -0.016053         -0.032082          -0.013674   
EmpWorkLifeBalance           -0.019563         -0.044788           0.010276   
ExperienceYearsAtThisCompany  0.318852          0.021908           0.076332   
ExperienceYearsInCurrentRole  0.217163          0.019898           0.066672   
YearsSinceLastPromotion       0.228199          0.013246           0.054313   
YearsWithCurrManager          0.205098          0.017860           0.088988   
PerformanceRating            -0.040164         -0.046142           0.020529   

                              EmpEnvironmentSatisfaction  EmpHourlyRate  \
Age                                             0.013814       0.062867   
DistanceFromHome                               -0.017719       0.013730   
EmpEducationLevel                              -0.037103       0.014095   
EmpEnvironmentSatisfaction                      1.000000      -0.049501   
EmpHourlyRate                                  -0.049501       1.000000   
EmpJobInvolvement                               0.004865       0.054741   
EmpJobLevel                                    -0.008272      -0.018606   
EmpJobSatisfaction                             -0.004319      -0.066417   
NumCompaniesWorked                              0.017270       0.040484   
EmpLastSalaryHikePercent                       -0.047271      -0.015934   
EmpRelationshipSatisfaction                    -0.010504       0.008783   
TotalWorkExperienceInYears                     -0.012894       0.026034   
TrainingTimesLastYear                           0.001192      -0.024160   
EmpWorkLifeBalance                             -0.000262       0.016189   
ExperienceYearsAtThisCompany                   -0.000561      -0.000399   
ExperienceYearsInCurrentRole                    0.025491      -0.011871   
YearsSinceLastPromotion                         0.010732      -0.010000   
YearsWithCurrManager                           -0.011702      -0.004576   
PerformanceRating                               0.395561      -0.043116   

                              EmpJobInvolvement  EmpJobLevel  \
Age                                    0.027216     0.509139   
DistanceFromHome                       0.003231     0.017270   
EmpEducationLevel                      0.027544     0.100734   
EmpEnvironmentSatisfaction             0.004865    -0.008272   
EmpHourlyRate                          0.054741    -0.018606   
EmpJobInvolvement                      1.000000    -0.034349   
EmpJobLevel                           -0.034349     1.000000   
EmpJobSatisfaction                    -0.005501    -0.011853   
NumCompaniesWorked                     0.018211     0.127477   
EmpLastSalaryHikePercent              -0.001742    -0.020975   
EmpRelationshipSatisfaction            0.018037     0.002992   
TotalWorkExperienceInYears            -0.028851     0.784229   
TrainingTimesLastYear                 -0.025168    -0.000389   
EmpWorkLifeBalance                    -0.014129     0.049

From the above Correlation between features with numerical values in the dataset.The signatures show the level of correlation from 0 to 1. From this distribution we can derive the facts as follows,

1. The Total years of experience and job level are having the higher correlation when comparing to all features.

2. Experience years at this company and years with the current manager has the second higher relation between these features.

3. Experience years at this company and experience in the current role,Total work experience in years, Year since last promotion, employee work life balance makes the sense of correlation.

4. People who have more experience with the company has the more probability to get the promotion from the correlation between them.

5. The age has the important role in the total number of work experience of an employee and the Employee Job level where it is a universal truth.

6. Employee Environment Satisfaction, Employee Last Salary hike percent, employee work life balance are having correlation with Performance rating.